name: CI
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Prepare integration test environment
      run: docker run -d --name etcd-server --publish 2379:2379 --publish 2380:2380 --env ALLOW_NONE_AUTHENTICATION=yes --env ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379 bitnami/etcd:latest

    - name: Integration Test
      run: yarn test:integrations

    - name: Publish
      run: cp .npmrc.template ~/.npmrc && npm publish --access public
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}